//check bookings
export const CHECK_BOOKING_REQUEST = 'CHECK_BOOKING_REQUEST';
export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS';
export const CHECK_BOOKING_FAILED = 'CHECK_BOOKING_FAILED';
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET';

//booked dates
export const BOOKED_DATES_SUCCESS = 'BOOKED_DATES_SUCCESS';
export const BOOKED_DATES_FAILED = 'BOOKED_DATES_FAILED';

//my bookings
export const MY_BOOKINGS_SUCCESS = 'MY_BOOKINGS_SUCCESS';
export const MY_BOOKINGS_FAILED = 'MY_BOOKINGS_FAILED';

//booking details
export const BOOKINGS_DETAILS_SUCCESS = 'BOOKINGS_DETAILS_SUCCESS';
export const BOOKINGS_DETAILS_FAILED = 'BOOKINGS_DETAILS_FAILED';

//all admin bookings
export const ADMIN_BOOKINGS_REQUEST = 'ADMIN_BOOKINGS_REQUEST';
export const ADMIN_BOOKINGS_SUCCESS = 'ADMIN_BOOKINGS_SUCCESS';
export const ADMIN_BOOKINGS_FAILED = 'ADMIN_BOOKINGS_FAILED';

//delete booking

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILED = 'DELETE_BOOKING_FAILED';
export const  DELETE_BOOKING_RESET = 'DELETE_BOOKING_RESET';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';