//register user

export const  REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const  REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const  REGISTER_USER_FAILED =  'REGISTER_USER_FAILED';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//load user
export const  LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const  LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const  LOAD_USER_FAILED =  'LOAD_USER_FAILED';

//update user profile
export const  UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const  UPDATE_USER_FAILED =  'UPDATE_USER_FAILED';
export const  UPDATE_USER_RESET =   'UPDATE_USER_RESET';

//Forgot password profile

export const  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_FAILED =  'FORGOT_PASSWORD_FAILED';


//Reset password profile
export const  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const  RESET_PASSWORD_FAILED =  'RESET_PASSWORD_FAILED';

//admin users

export const  ADMIN_USERS_REQUEST = 'ADMIN_USERS_REQUEST';
export const  ADMIN_USERS_SUCCESS = 'ADMIN_USERS_SUCCESS';
export const  ADMIN_USERS_FAILED =  'ADMIN_USERS_FAILED';


//user details
export const  USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const  USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const  USER_DETAILS_FAILED =  'USER_DETAILS_FAILED';

//update users
export const  UPDATE_AGENT_REQUEST = 'UPDATE_AGENT_REQUEST';
export const  UPDATE_AGENT_SUCCESS = 'UPDATE_AGENT_SUCCESS';
export const  UPDATE_AGENT_FAILED =  'UPDATE_AGENT_FAILED';
export const  UPDATE_AGENT_RESET =   'UPDATE_AGENT_RESET';



//delete user
export const  DELETE_AGENT_REQUEST = 'DELETE_AGENT_REQUEST';
export const  DELETE_AGENT_SUCCESS = 'DELETE_AGENT_SUCCESS';
export const  DELETE_AGENT_FAILED =  'DELETE_AGENT_FAILED';
export const  DELETE_AGENT_RESET =  'DELETE_AGENT_RESET';





